version: "3.8"

services:
  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: dbapp
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
    ports:
      - "3306:3306"

  backend:
    build: ./backend/app
    restart: always
    container_name: myapp
    depends_on:
      - mysql
    environment:
      - SQLALCHEMY_DATABASE_URL=mysql+pymysql://dbuser:dbpassword@mysql:3306/dbapp
    ports:
      - "8000:80"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    restart: always
    container_name: frontend
    ports:
      - "3000:3000"

