name: Docker Compose Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker images
        run: docker-compose -f docker-compose.yml build

      - name: Push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: username/repository:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy with Docker Compose
        run: docker-compose -f docker-compose.yml up -d
