name: Docker Compose Build and Deploy

on:
  push:
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker images
        run: docker-compose -f docker-compose.yaml build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./backend/app
          file: ./backend/app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/backend-image:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend-image:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Deploy with Docker Compose
        run: docker-compose -f docker-compose.yaml up -d
